name: sofy_new
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+15

environment:
  sdk: ">=2.4.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio_http_cache:
    path: ./local_packages/dio_http_cache
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  badges: ^2.0.1
  flutter_swiper: ^1.1.6
  flutter_xlider: ^3.4.0
  flutter_svg: ^0.22.0
  gradient_widgets: ^0.6.0
  fl_chart: ^0.36.2
  provider: ^5.0.0

  flutter_neumorphic: ^3.1.0
  shared_preferences: ^2.0.6
  intl: ^0.17.0
  cached_network_image: ^3.0.0
  rate_my_app: ^1.1.0+1
  in_app_review: ^2.0.2
  url_launcher: ^6.0.7
  share: ^2.0.4
  percent_indicator: ^3.3.0-nullsafety.1
  flutter_simple_rating_bar: ^0.0.3
  fluttertoast: ^8.0.7
  focus_detector: ^2.0.0
  image_picker: ^0.7.4
  image_fade: ^0.2.1
  shimmer: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  infinity_page_view: ^1.0.0
  flutter_bloc: ^7.0.1
  bloc: ^7.0.0
  extended_image: ^4.1.0

  qonversion_flutter: ^3.2.1

  flutter_html: ^2.1.0

  flutter_local_notifications: ^7.0.0-dev.1
  firebase_messaging: ^10.0.2

  firebase_core: ^1.3.0
  visibility_detector: ^0.2.0
  rflutter_alert: ^2.0.2
  # Analytics
  device_id: ^0.2.0
  appmetrica_sdk: ^0.0.7
  amplitude_flutter: ^3.1.1
  firebase_analytics: ^8.1.2
  facebook_app_events: ^0.12.0
  uuid: ^3.0.4
  tenjin_sdk: ^1.0.1
  app_tracking_transparency: ^2.0.1
  firebase_remote_config: ^0.10.0+2
  fluid_bottom_nav_bar: ^1.3.0
  curved_navigation_bar: ^1.0.1
  font_awesome_flutter: ^9.1.0
  flutter_screenutil: ^5.0.0+2
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/svg/
    - assets/ava/
    - assets/vibration_icons/
    - i18n/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  fonts:
    - family: Exo 2
      fonts:
        - asset: fonts/Roboto-Bold.ttf
    - family: Proxima Nova
      fonts:
        - asset: fonts/FontsFree-Net-proxima_nova_reg-webfont.ttf
    - family: Gilroy
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Gilroy Bold
      fonts:
        - asset: fonts/Roboto-Bold.ttf
    - family: Gilroy Black
      fonts:
        - asset: fonts/Roboto-Black.ttf
    - family: Montserrat Bold
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
    - family: Montserrat Semi
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
  # New main page fonts
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Roboto Bold
      fonts:
          - asset: fonts/Roboto-Bold.ttf
    - family: Hind Guntur Bold
      fonts:
        - asset: fonts/HindGuntur-Bold.ttf
    - family: Hind Guntur SemiBold
      fonts:
        - asset: fonts/HindGuntur-SemiBold.ttf
    - family: Hind Guntur
      fonts:
        - asset: fonts/HindGuntur-Regular.ttf
    - family: Hind Guntur Medium
      fonts:
        - asset: fonts/HindGuntur-Medium.ttf
    - family: Abhaya Libre ExtraBold
      fonts:
        - asset: fonts/AbhayaLibre-ExtraBold.ttf
    - family: Allerta
      fonts:
        - asset: fonts/allerta_medium.ttf
    - family: SF Pro Medium
      fonts:
        - asset: fonts/SFProDisplay-Medium.ttf
    - family: SF Pro Bold
      fonts:
        - asset: fonts/SFProDisplay-Bold.ttf
    - family: Raleway Regular
      fonts:
        - asset: fonts/Raleway-Regular.ttf
    - family: Raleway Medium
      fonts:
        - asset: fonts/Raleway-Medium.ttf
    - family: Raleway SemiBold
      fonts:
        - asset: fonts/Raleway-SemiBold.ttf
    - family: Raleway Bold
      fonts:
        - asset: fonts/Raleway-Bold.ttf
    - family: Exo 2 Bold
      fonts:
        - asset: fonts/Exo2-Bold.ttf
    - family: Gilroy1
      fonts:
        - asset: fonts/Gilroylight.ttf