name: sofy_new
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+9

environment:
  sdk: ">=2.4.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio_http_cache:
    path: ./local_packages/dio_http_cache
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  badges: ^1.1.4
  flutter_swiper: ^1.1.6
  flutter_xlider: ^3.1.1
  flutter_svg: ^0.21.0-nullsafety.0
  gradient_widgets: ^0.5.2
  fl_chart: ^0.30.0
  provider: ^5.0.0

  flutter_neumorphic: ^3.0.4+1
  shared_preferences: ^2.0.5
  intl: ^0.17.0
  cached_network_image: ^2.5.0
  rate_my_app: ^1.0.0+2
  in_app_review: ^2.0.1
  url_launcher: ^6.0.3
  share: ^2.0.1
  percent_indicator: ^2.1.9+1
  flutter_simple_rating_bar: ^0.0.3
  fluttertoast: ^8.0.3
  focus_detector: ^2.0.0
  image_picker: ^0.7.4
  image_fade: ^0.2.1
  shimmer: ^1.1.2
  auto_size_text: ^2.1.0
  infinity_page_view: ^1.0.0

  qonversion_flutter: ^3.2.1

  flutter_html: ^2.0.0-nullsafety.0

  flutter_local_notifications: ^5.0.0
  firebase_messaging: ^9.1.0

  firebase_core: ^1.0.2
  firebase_remote_config: ^0.10.0-dev.2

  # Analytics
  device_id: ^0.2.0
  appmetrica_sdk: ^0.0.6
  amplitude_flutter: ^3.0.0
  firebase_analytics: ^7.0.0
  facebook_app_events: ^0.11.0
  uuid: ^3.0.3
  tenjin_sdk: ^1.0.1
  app_tracking_transparency: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/svg/
    - assets/ava/
    - i18n/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  fonts:
    - family: Exo 2
      fonts:
        - asset: fonts/Roboto-Bold.ttf
    - family: Proxima Nova
      fonts:
        - asset: fonts/FontsFree-Net-proxima_nova_reg-webfont.ttf
    - family: Gilroy
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Gilroy Bold
      fonts:
        - asset: fonts/Roboto-Bold.ttf
    - family: Gilroy Black
      fonts:
        - asset: fonts/Roboto-Black.ttf
    - family: Montserrat Bold
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
    - family: Montserrat Semi
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf